sudo: required
services:
  - docker

before_install:
  - docker build -t iamanh/react-test -f ./client/Dockerfile.dev ./client
script: 
  - docker run -e CI=true iamanh/react-test npm test
after_success: 
  - docker build -t iamanh/multi-client ./client
  - docker build -t iamanh/multi-nginx ./nginx
  - docker build -t iamanh/multi-server ./server
  - docker build -t iamanh/multi-worker ./worker
